listeners:
  default:
    type: tcp
    bind: 0.0.0.0:1883
sys_interval: 20
auth:
  allow-anonymous: true
  plugins:
    - auth_anonymous
topic-check:
  acl:
    anonymous:
      - "#"
      - "agv/#"
      - "base_status"
      - "task_feedback"
      - "feedback"
      - "robot_control"
