float64 linear_velocity
float64 angular_velocity

int16 front_left_speed
int16 front_right_speed
int16 back_left_speed
int16 back_right_speed

float32 front_left_current
float32 front_right_current
float32 back_left_current
float32 back_right_current

float32 front_voltage
float32 back_voltage

float32 voltage

bool stop_button
bool software_stop
bool remote_ctrl_stop

bool front_collision
bool back_collision

bool charge_enable
uint8 charge_state

bool remote_ctrl_error
bool voltage_error
bool drive_error